import { Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} antialiased relative`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
